version: "3.4"
configs:
  traefik:
    external:
      name: traefik
services:
  client:
    image: rodrwan/madams:v0.0.1
    depends_on:
      - server
    labels:
      traefik.backend: client
      traefik.frontend.rule: "Host:www.forecast.acid.com"
      traefik.frontend.entryPoints: "http"
      traefik.docker.network=: "public"
      traefik.enable: "true"
    hostname: madams
    restart: always
    ports:
      - "80:80"
    environment:
      REACT_APP_GOOGLE_MAPS_TOKEN: AIzaSyDTVwuTYgHeQ0IhKWkQTxK4TkyvFmqa9r8
      REACT_APP_GMARCONE_API_URL: https://dockhero-rugged-50468-flexible-ssl.dockhero.io:3001
      REACT_APP_TRAEFIK_HOST: api.forecast.acid.com
  server:
    image: rodrwan/gmarcone:v0.0.1
    depends_on:
      - redis
    labels:
      traefik.frontend.rule: "Host:api.forecast.acid.com"
      traefik.backend: "server"
      traefik.docker.network=: "public"
      traefik.enable: "true"
      traefik.port: "3001"
      traefik.frontend.entryPoints: "http"
    hostname: gmarcone
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      REDIS_PORT: 6379
      REDIS_HOST: redis
      DARKSKY_API_URL: https://api.darksky.net/forecast
      DARKSKY_TOKEN: ffcc7b40af981c3e93afb60902083bf2
      DARKSKY_API_CALLS: 1000
      GEOCODE_API_URL: https://maps.googleapis.com/maps/api/geocode/json
      GEOCODE_API_TOKEN: AIzaSyAOt5c4hCHvioYKNXVARGOKUqSv8hdgCP4
      CACHE_INTERVAL: 87
  redis:
    image: redis:alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"
  traefik:
    image: traefik
    depends_on:
      - server
    volumes:
      - /dev/null:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    command: --web \
      --docker \
      --docker.domain=docker.localhost \
      --docker.watch \
      --logLevel=DEBUG
    ports:
      - "8081:80"
      - "443:443"
      - "8080:8080"
    tty: true
